config/routes.rb
Saosao::Application.routes.draw do
  root :to => "home#index"
  
  match "/twitter_signin_callback" => "home#twitter_signin_callback", :as => :twitter_signin_callback
  
  post "/unfollow" => "home#unfollow", :as => :unfollow_followees
  
  match "/search" => "home#search", :as => :search
  post "/follow" => "home#follow", :as => :follow
  
  match "/sign_out" => "home#sign_out", :as => :sign_out

end

app/controllers/home_controller.rb
require 'openssl'
require 'digest/sha1'

class HomeController < ApplicationController
  
  # GET /
  def index
    if !session[:screen_name]
      # Saving the token and token secret for future use
      session[:oauth_token], oauth_token_secret = Twitter.obtain_request_token
      
      # Setting the twitter authentication url
      @login_url = "https://api.twitter.com/oauth/authenticate?oauth_token=" + session[:oauth_token]
    else
      page = params[:page] || 1
      @followees = Twitter.followees(session[:screen_name], page.to_i)
      @totals = Twitter.totals(session[:screen_name])
    end
  end

  # GET /twitter_signin_callback
  def twitter_signin_callback
    # Checking if the tokens match
    if params[:oauth_token] == session[:oauth_token]
      # Getting the user's data (screen_name and user_id)
      user_data = Twitter.user_info(params[:oauth_verifier], session[:oauth_token])
      
      # Creating a random_iv to be used in the encryption process
      session[:random_iv] = OpenSSL::Cipher::Cipher.new("aes-256-cbc").random_iv
      
      # Encrypting the attributes for security reasons
      encrypt_session_attribute(user_data[:screen_name], :oauth_token, user_data[:oauth_token])
      encrypt_session_attribute(user_data[:screen_name], :oauth_token_secret, user_data[:oauth_token_secret])

      session[:screen_name] = user_data[:screen_name]
      
      redirect_to root_path
    else
      # Hacking
      flash[:warning] = "Not authorized access!"
      redirect_to root_path
    end
  end
  
  # POST /unfollow
  def unfollow
    # Decrypting the attributes
    oauth_token = decrypt_session(session[:screen_name], :oauth_token)
    oauth_token_secret = decrypt_session(session[:screen_name], :oauth_token_secret)
    
    params[:followees_ids].each do |followee_id|
      Twitter.unfollow(oauth_token, oauth_token_secret, followee_id)
    end
    
    flash[:success] = "Successfully unfollowed #{params[:followees_ids].count} followee(s)!"
    redirect_to root_path
  end
  
  # POST /search
  def search
    @users = Twitter.search(params[:search], session[:screen_name], params[:page] || 1)
  end
  
  # POST /follow
  def follow
    # Decrypting the attributes
    oauth_token = decrypt_session(session[:screen_name], :oauth_token)
    oauth_token_secret = decrypt_session(session[:screen_name], :oauth_token_secret)
    
    params[:users_screen_names].each do |user_screen_name|
      Twitter.follow(oauth_token, oauth_token_secret, user_screen_name)
    end
    
    flash[:success] = "Successfully followed #{params[:users_screen_names].count} followee(s)!"
    redirect_to root_path
  end
  
  # GET /sign_out
  def sign_out
    # Decrypting the attributes
    oauth_token = decrypt_session(session[:screen_name], :oauth_token)
    oauth_token_secret = decrypt_session(session[:screen_name], :oauth_token_secret)
    
    # Signing out from Twitter
    Twitter.sign_out(oauth_token, oauth_token_secret)
    
    # Clearing the user's data saved in the session
    session.delete(:oauth_token)
    session.delete(:oauth_token_secret)
    session.delete(:screen_name)
    session.delete(:random_iv)
    
    flash[:success] = "Signed out sucessfully!"
    redirect_to root_path
  end
  
  private
  def encrypt_session_attribute(user_screen_name, session_attribute_name, session_attribute_value)
    cipher = OpenSSL::Cipher::Cipher.new("aes-256-cbc")
    cipher.encrypt
    
    cipher.key = Digest::SHA1.hexdigest(user_screen_name)
    cipher.iv = session[:random_iv]
    
    # encrypt the message
    encrypted = cipher.update(session_attribute_value)
    encrypted << cipher.final
    
    cipher.decrypt
    
    cipher.key = Digest::SHA1.hexdigest(user_screen_name)

    session[session_attribute_name] = encrypted
  end
  
  def decrypt_session(user_screen_name, session_attribute_name)
    cipher = OpenSSL::Cipher::Cipher.new("aes-256-cbc")
    cipher.decrypt
    
    cipher.key = Digest::SHA1.hexdigest(user_screen_name)
    cipher.iv = session[:random_iv]
    
    # and decrypt it
    decrypted = cipher.update(session[session_attribute_name])
    decrypted << cipher.final
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
- if @login_url
  .sign_in_with_twitter.light
    %div
    = link_to @login_url do
      .icon
      .login 
        Sign in with Twitter

- else
  .well
    = "You are following #{pluralize(@totals[:followers], 'follower')} and have #{pluralize(@totals[:followees], 'followee')} " 
  
  %table.table.projects
    %thead
      %tr
        %td
        %th Screen Name
        %th Unfollow?
    %tbody
      = form_tag unfollow_followees_path, :html => { :class => 'form-horizontal' } do
        - @followees.each do |followee|
          %tr
            %td= image_tag followee["profile_image_url_https"]
            %td= link_to followee["name"], "http://twitter.com/#!/#{followee['screen_name']}"
            %td= check_box_tag "followees_ids[]", followee["id"]
        
        %tr
          %td
          %td
          %td= submit_tag "Unfollow checked", :class => 'btn btn-danger'
            
  #pagination
    
  :javascript
    paginate(#{(@totals[:followers] / 20.0).ceil}, #{params[:page] || 1});
    
    

app/views/home/search.html.haml
%table.table.projects
  %thead
    %tr
      %th Screen Name
      %th Follow?
  %tbody
    = form_tag follow_path, :html => { :class => 'form-horizontal' } do
      - @users.each do |user|
        %tr
          %td= link_to user, "https://twitter.com/#!/#{user}"
          %td= check_box_tag "users_screen_names[]", user
      
      %tr
        %td
        %td= submit_tag "Follow checked", :class => 'btn btn-success'
          
#pagination
  
:javascript
  paginate(20, #{params[:page] || 1});

app/views/home/twitter_signin.html.erb
<h1>Home#twitter_signin</h1>
<p>Find me in app/views/home/twitter_signin.html.erb</p>