config/routes.rb
Saosao::Application.routes.draw do
  root :to => "home#index"
  
  match "/twitter_signin_callback" => "home#twitter_signin_callback", :as => :twitter_signin_callback
  
  post "/unfollow" => "home#unfollow", :as => :unfollow_followees
  
  match "/search" => "home#search", :as => :search
  post "/follow" => "home#follow", :as => :follow
  
  match "/sign_out" => "home#sign_out", :as => :sign_out

end

app/views/layouts/_menu.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      
      = link_to "Saosao", root_path, :class => "brand"
      
      .nav-collapse
        - if session[:screen_name]
          %ul.nav.pull-right
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Welcome, #{session[:screen_name]}
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Sign out", sign_out_path

        = form_tag search_path, :class => "navbar-search pull-right", :method => :get do
          = text_field_tag "search", nil, :class => "search-query", :placeholder => "Search"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Saosao
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application", "jquery.paginate", "jquery.ba-bbq"
    = csrf_meta_tags
  %body
    = render 'layouts/menu'
    
    .container
      .row
        .span6.offset3
          - flash.each do |key ,value|
            %div{:class => "alert fade in  alert-#{key == :notice ? 'success' : key}"}
              %a.close{"data-dismiss" => "alert", :href => "#"} ×
              = value
          = yield
          
        .span3